import type { Estado } from '@/types'

export const estados: Estado[] = [
  { id: 0, uf: 'BR', nome: 'Brasil', icone: '/img/bandeiras/circle/brasil.svg' },
  { id: 1, uf: 'AC', nome: 'Acre', icone: '/img/bandeiras/circle/acre.svg' },
  { id: 2, uf: 'AL', nome: 'Alagoas', icone: '/img/bandeiras/circle/alagoas.svg' },
  { id: 3, uf: 'AP', nome: 'Amapá', icone: '/img/bandeiras/circle/amapa.svg' },
  { id: 4, uf: 'AM', nome: 'Amazonas', icone: '/img/bandeiras/circle/amazonas.svg' },
  { id: 5, uf: 'BA', nome: 'Bahia', icone: '/img/bandeiras/circle/bahia.svg' },
  { id: 6, uf: 'CE', nome: 'Ceará', icone: '/img/bandeiras/circle/ceara.svg' },
  { id: 7, uf: 'DF', nome: 'Distrito Federal', icone: '/img/bandeiras/circle/distrito-federal.svg' },
  { id: 8, uf: 'ES', nome: 'Espírito Santo', icone: '/img/bandeiras/circle/espirito-santo.svg' },
  { id: 9, uf: 'GO', nome: 'Goías', icone: '/img/bandeiras/circle/goias.svg' },
  { id: 10, uf: 'MA', nome: 'Maranhão', icone: '/img/bandeiras/circle/maranhao.svg' },
  { id: 11, uf: 'MT', nome: 'Mato Grosso', icone: '/img/bandeiras/circle/mato-grosso.svg' },
  { id: 12, uf: 'MS', nome: 'Mato Grosso do Sul', icone: '/img/bandeiras/circle/mato-grosso-do-sul.svg' },
  { id: 13, uf: 'MG', nome: 'Minas Gerais', icone: '/img/bandeiras/circle/minas-gerais.svg' },
  { id: 14, uf: 'PA', nome: 'Pará', icone: '/img/bandeiras/circle/para.svg' },
  { id: 15, uf: 'PB', nome: 'Paraíba', icone: '/img/bandeiras/circle/paraiba.svg' },
  { id: 16, uf: 'PR', nome: 'Paraná', icone: '/img/bandeiras/circle/parana.svg' },
  { id: 17, uf: 'PE', nome: 'Pernambuco', icone: '/img/bandeiras/circle/pernambuco.svg' },
  { id: 18, uf: 'PI', nome: 'Piauí', icone: '/img/bandeiras/circle/piaui.svg' },
  { id: 19, uf: 'RJ', nome: 'Rio de Janeiro', icone: '/img/bandeiras/circle/rio-de-janeiro.svg' },
  { id: 20, uf: 'RN', nome: 'Rio Grande do Norte', icone: '/img/bandeiras/circle/rio-grande-do-norte.svg' },
  { id: 21, uf: 'RS', nome: 'Rio Grande do Sul', icone: '/img/bandeiras/circle/rio-grande-do-sul.svg' },
  { id: 22, uf: 'RO', nome: 'Rondônia', icone: '/img/bandeiras/circle/rondonia.svg' },
  { id: 23, uf: 'RR', nome: 'Roraíma', icone: '/img/bandeiras/circle/roraima.svg' },
  { id: 24, uf: 'SC', nome: 'Santa Catarina', icone: '/img/bandeiras/circle/santa-catarina.svg' },
  { id: 25, uf: 'SP', nome: 'São Paulo', icone: '/img/bandeiras/circle/sao-paulo.svg' },
  { id: 26, uf: 'SE', nome: 'Sergipe', icone: '/img/bandeiras/circle/sergipe.svg' },
  { id: 27, uf: 'TO', nome: 'Tocantins', icone: '/img/bandeiras/circle/tocantins.svg' }  
]