import type { Estado } from '@/types'

export const estados: Estado[] = [
  { id: 0, sigla: 'BR', nome: 'Brasil', icone: '/img/bandeiras/circle/brasil.svg' },
  { id: 1, sigla: 'AC', nome: 'Acre', icone: '/img/bandeiras/circle/acre.svg' },
  { id: 2, sigla: 'AL', nome: 'Alagoas', icone: '/img/bandeiras/circle/alagoas.svg' },
  { id: 3, sigla: 'AP', nome: 'Amapá', icone: '/img/bandeiras/circle/amapa.svg' },
  { id: 4, sigla: 'AM', nome: 'Amazonas', icone: '/img/bandeiras/circle/amazonas.svg' },
  { id: 5, sigla: 'BA', nome: 'Bahia', icone: '/img/bandeiras/circle/bahia.svg' },
  { id: 6, sigla: 'CE', nome: 'Ceará', icone: '/img/bandeiras/circle/ceara.svg' },
  { id: 7, sigla: 'DF', nome: 'Distrito Federal', icone: '/img/bandeiras/circle/distrito-federal.svg' },
  { id: 8, sigla: 'ES', nome: 'Espírito Santo', icone: '/img/bandeiras/circle/espirito-santo.svg' },
  { id: 9, sigla: 'GO', nome: 'Goías', icone: '/img/bandeiras/circle/goias.svg' },
  { id: 10, sigla: 'MA', nome: 'Maranhão', icone: '/img/bandeiras/circle/maranhao.svg' },
  { id: 11, sigla: 'MT', nome: 'Mato Grosso', icone: '/img/bandeiras/circle/mato-grosso.svg' },
  { id: 12, sigla: 'MS', nome: 'Mato Grosso do Sul', icone: '/img/bandeiras/circle/mato-grosso-do-sul.svg' },
  { id: 13, sigla: 'MG', nome: 'Minas Gerais', icone: '/img/bandeiras/circle/minas-gerais.svg' },
  { id: 14, sigla: 'PA', nome: 'Pará', icone: '/img/bandeiras/circle/para.svg' },
  { id: 15, sigla: 'PB', nome: 'Paraíba', icone: '/img/bandeiras/circle/paraiba.svg' },
  { id: 16, sigla: 'PR', nome: 'Paraná', icone: '/img/bandeiras/circle/parana.svg' },
  { id: 17, sigla: 'PE', nome: 'Pernambuco', icone: '/img/bandeiras/circle/pernambuco.svg' },
  { id: 18, sigla: 'PI', nome: 'Piauí', icone: '/img/bandeiras/circle/piaui.svg' },
  { id: 19, sigla: 'RJ', nome: 'Rio de Janeiro', icone: '/img/bandeiras/circle/rio-de-janeiro.svg' },
  { id: 20, sigla: 'RN', nome: 'Rio Grande do Norte', icone: '/img/bandeiras/circle/rio-grande-do-norte.svg' },
  { id: 21, sigla: 'RS', nome: 'Rio Grande do Sul', icone: '/img/bandeiras/circle/rio-grande-do-sul.svg' },
  { id: 22, sigla: 'RO', nome: 'Rondônia', icone: '/img/bandeiras/circle/rondonia.svg' },
  { id: 23, sigla: 'RR', nome: 'Roraíma', icone: '/img/bandeiras/circle/roraima.svg' },
  { id: 24, sigla: 'SC', nome: 'Santa Catarina', icone: '/img/bandeiras/circle/santa-catarina.svg' },
  { id: 25, sigla: 'SP', nome: 'São Paulo', icone: '/img/bandeiras/circle/sao-paulo.svg' },
  { id: 26, sigla: 'SE', nome: 'Sergipe', icone: '/img/bandeiras/circle/sergipe.svg' },
  { id: 27, sigla: 'TO', nome: 'Tocantins', icone: '/img/bandeiras/circle/tocantins.svg' }  
]