- name: "Alterar as unidades do systemd"
  ansible.builtin.copy:
    src: "files/etc/systemd/system/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - agrocomm-hono.service
    - agrocomm-scrape.service
    - agrocomm-scrape.timer
  notify: Reload systemd

- name: "Aguardar a unidade estar disponível"
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop:
    - agrocomm-hono.service
    - agrocomm-scrape.service
    - agrocomm-scrape.timer


- name: >-
    Allow the alice user to run sudo /bin/systemctl restart agrocomm-hono.service or
    sudo /usr/bin/systemctl reload agrocomm-hono.service, password is not required
  community.general.sudoers:
    name: agrocomm-hono
    user: nginx
    commands:
      - /usr/bin/systemctl stop agrocomm-hono.service
      - /usr/bin/systemctl start agrocomm-hono.service
      - /usr/bin/systemctl restart agrocomm-hono.service
    nopassword: true


- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
