---
- name: Update systemd unit and reload daemon
  hosts: all 
  become: true
  remote_user: root

  vars:
    #ansible_ssh_user: 'rohit'
    #ansible_password: '123456'
    ansible_port: '2200'

  tasks:
    - name: "Alterar as unidades do systemd"
      ansible.builtin.copy:
        src: "files/etc/systemd/system/{{ item }}"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - agrocomm-hono.service
        - agrocomm-scrape.service
        - agrocomm-scrape.timer
      notify: Reload systemd

    - name: "Aguardar a unidade estar disponível"
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
        enabled: true
      loop:
        - agrocomm-hono.service
        - agrocomm-scrape.service
        - agrocomm-scrape.timer

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
