# path: /etc/nginx/sites-available/agrocomm.com.br

server {
    listen 80;
    listen [::]:80;
    server_name *.agrocomm.com.br agrocomm.com.br;
    return 301 https://agrocomm.com.br$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    ssl_certificate         /etc/letsencrypt/live/agrocomm.com.br/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/agrocomm.com.br/privkey.pem;

    server_name www.agrocomm.com.br;
    return 301 https://agrocomm.com.br$request_uri;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;

    ssl_certificate         /etc/letsencrypt/live/agrocomm.com.br/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/agrocomm.com.br/privkey.pem;

    server_name agrocomm.com.br;
    root /var/www/agrocomm/apps/site/dist;

    include conf.d/cache.conf;
    include conf.d/errors.conf;

    location / {
        try_files $uri $uri/ /index.html =500;
    }
}
